// Generated by CoffeeScript 1.9.3
(function() {
  var bookController, bookListController, cardController, creditController, editUserController, examController, failRateController, hnust, judgeController, lastUserController, loginController, navbarController, scheduleController, scoreAllController, scoreController, sortByFilter, tuitionController, userController,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  hnust = angular.module('hnust', ['ngRoute']);

  hnust.factory('checkJsonpData', function($rootScope, $location) {
    return {
      check: function(data) {
        if (!angular.isObject(data)) {
          data = {
            code: -1
          };
        }
        switch (data.code) {
          case -2:
            $rootScope.user = {
              name: '游客',
              rank: -1
            };
            $rootScope.referer = $location.url();
            $location.url('/login');
            break;
          case -1:
            $rootScope.error = data.msg || '网络连接超时 OR 服务器错误。';
            break;
          case 1:
            layer.msg(data.msg);
            break;
          case 2:
            layer.open({
              title: data.msg,
              content: data.data
            });
            break;
          case 3:
            if ($rootScope.referer && $rootScope.referer !== '/login') {
              $location.url($rootScope.referer);
              $rootScope.referer = '';
            } else {
              $location.url('/score');
            }
        }
        if (data.code >= 0) {
          return true;
        } else {
          return false;
        }
      }
    };
  });

  hnust.factory('getJsonpData', function($rootScope, $http, $location, checkJsonpData) {
    return {
      query: function(params, timeout, callback) {
        var bgjsonp, ref, search, self;
        self = this;
        $rootScope.error = '';
        search = angular.copy($location.search());
        search.fun || (search.fun = $rootScope.fun);
        params = $.extend(search, params);
        params.callback = 'JSON_CALLBACK';
        bgjsonp = ['user', 'failRateKey', 'bookInfo'];
        timeout || (timeout = 8000);
        if (ref = params.fun, indexOf.call(bgjsonp, ref) < 0) {
          $rootScope.loading = true;
        }
        return $http.jsonp($rootScope.url, {
          params: params,
          timeout: timeout
        }).success(function(res) {
          var ref1;
          if (ref1 = params.fun, indexOf.call(bgjsonp, ref1) < 0) {
            $rootScope.loading = false;
          }
          res.code = parseInt(res.code);
          if (!checkJsonpData.check(res)) {

          } else if (res.code === 4) {
            params.passwd = prompt(res.msg, '');
            if (params.passwd) {
              return self.query(params, timeout, callback);
            } else {
              return $rootScope.error = '密码错误！';
            }
          } else if (callback != null) {
            return callback(res);
          }
        }).error(function() {
          var ref1;
          if (ref1 = params.fun, indexOf.call(bgjsonp, ref1) < 0) {
            $rootScope.loading = false;
          }
          return checkJsonpData.check({
            code: -1,
            msg: '网络异常，请稍后再试。'
          });
        });
      }
    };
  });

  hnust.config(function($httpProvider, $routeProvider) {
    return $routeProvider.when('/login', {
      fun: 'login',
      title: '用户登录',
      controller: 'login',
      templateUrl: 'views/login.html?150723'
    }).when('/agreement', {
      fun: 'agreement',
      title: '用户使用协议',
      templateUrl: 'views/agreement.html?150723'
    }).when('/user', {
      fun: 'user',
      title: '用户中心',
      controller: 'user',
      templateUrl: 'views/user.html?150801'
    }).when('/score', {
      fun: 'score',
      title: '成绩查询',
      controller: 'score',
      templateUrl: 'views/score.html?150806'
    }).when('/scoreAll', {
      fun: 'scoreAll',
      title: '全班成绩',
      controller: 'scoreAll',
      templateUrl: 'views/scoreAll.html?150801'
    }).when('/schedule', {
      fun: 'schedule',
      title: '实时课表',
      controller: 'schedule',
      templateUrl: 'views/schedule.html?150723'
    }).when('/exam', {
      fun: 'exam',
      title: '考试安排',
      controller: 'exam',
      templateUrl: 'views/exam.html?150723'
    }).when('/credit', {
      fun: 'credit',
      title: '学分绩点',
      controller: 'credit',
      templateUrl: 'views/credit.html?150723'
    }).when('/judge', {
      fun: 'judge',
      title: '教学评价',
      controller: 'judge',
      templateUrl: 'views/judge.html?150723'
    }).when('/book', {
      fun: 'book',
      title: '图书续借',
      controller: 'book',
      templateUrl: 'views/book.html?150723'
    }).when('/bookList', {
      fun: 'bookList',
      title: '图书检索',
      controller: 'bookList',
      templateUrl: 'views/bookList.html?150803'
    }).when('/tuition', {
      fun: 'tuition',
      title: '学年学费',
      controller: 'tuition',
      templateUrl: 'views/tuition.html?150723'
    }).when('/card', {
      fun: 'card',
      title: '校园一卡通',
      controller: 'card',
      templateUrl: 'views/card.html?150801'
    }).when('/failRate', {
      fun: 'failRate',
      title: '挂科率统计',
      controller: 'failRate',
      templateUrl: 'views/failRate.html?150803'
    }).when('/editUser', {
      fun: 'editUser',
      title: '修改权限',
      controller: 'editUser',
      templateUrl: 'views/editUser.html?150723'
    }).when('/lastUser', {
      fun: 'lastUser',
      title: '最近使用用户',
      controller: 'lastUser',
      templateUrl: 'views/lastUser.html?150723'
    }).otherwise({
      redirectTo: '/score'
    });
  });

  hnust.run(function($location, $rootScope, getJsonpData) {
    $rootScope.url = 'http://a.hnust.sinaapp.com/index.php';
    $rootScope.$on('$routeChangeSuccess', function(event, current, previous) {
      var ref, ref1;
      $rootScope.fun = ((ref = current.$$route) != null ? ref.fun : void 0) || '';
      return $rootScope.title = ((ref1 = current.$$route) != null ? ref1.title : void 0) || '';
    });
    return $rootScope.$on('updateUserInfo', function(event, current) {
      return getJsonpData.query({
        fun: 'user'
      }, 8000, function(data) {
        var base;
        data.info.id = data.info.studentId || '';
        (base = data.info).name || (base.name = '游客');
        data.info.rank = data.info.rank != null ? parseInt(data.info.rank) : -1;
        data.info.scoreRemind = !!parseInt(data.info.scoreRemind);
        return $rootScope.user = data.info;
      });
    });
  });

  navbarController = function($scope, $rootScope, getJsonpData) {
    $scope.isPhone = document.body.offsetWidth < 720;
    $scope.sidebar = $('.ui.sidebar');
    $scope.$watch(function() {
      var ref;
      return (ref = $rootScope.user) != null ? ref.rank : void 0;
    }, function() {
      if ($scope.isPhone) {
        return $scope.sidebar.sidebar('attach events', '#menu');
      } else {
        return $scope.sidebar.sidebar({
          closable: false,
          dimPage: false,
          scrollLock: true,
          transition: 'overlay'
        }).sidebar('attach events', '#menu');
      }
    });
    $scope.sidebarHide = function() {
      if ($scope.isPhone) {
        $scope.sidebar.sidebar('hide');
      }
    };
    $scope.hideNavbar = navigator.userAgent === 'demo';
    $scope.$emit('updateUserInfo');
    return $scope.logout = function() {
      return getJsonpData.query({
        fun: 'logout'
      });
    };
  };

  userController = function($scope, $rootScope, $location, getJsonpData) {
    var watch;
    $('.ui.checkbox').checkbox('check');
    $rootScope.error = '';
    $scope.scoreRemind = function(isCheck) {
      var ref;
      $scope.user.scoreRemind = isCheck != null ? isCheck : !((ref = $scope.user) != null ? ref.scoreRemind : void 0);
      if ($scope.user.scoreRemind === true) {
        $('.ui.checkbox').checkbox('check');
        $('#mailField').transition('slide down in');
        return $scope.user.mail = $rootScope.user.mail;
      } else {
        $('.ui.checkbox').checkbox('uncheck');
        $('#mailField').transition('slide down out');
        return $scope.user.mail = '';
      }
    };
    watch = $scope.$watch(function() {
      return $rootScope.user;
    }, function() {
      var ref;
      if ((((ref = $rootScope.user) != null ? ref.rank : void 0) != null) && $rootScope.user.rank !== -1) {
        $scope.user = angular.copy($rootScope.user);
        $scope.scoreRemind($scope.user.scoreRemind);
        return watch();
      }
    }, true);
    return $('.ui.form').form({
      mail: {
        identifier: 'mail',
        optional: true,
        rules: [
          {
            type: 'email',
            prompt: '请输入正确的邮件地址。'
          }
        ]
      }
    }, {
      inline: true,
      on: 'blur',
      onSuccess: function() {
        var params;
        params = {
          fun: 'userUpdate',
          scoreRemind: $scope.user.scoreRemind ? '1' : '0',
          mail: $scope.user.mail
        };
        getJsonpData.query(params, 8000, function(data) {
          return $scope.$emit('updateUserInfo');
        });
        return false;
      }
    });
  };

  loginController = function($scope, $rootScope, getJsonpData, checkJsonpData) {
    var ref;
    $('.ui.checkbox').checkbox();
    if ((((ref = $rootScope.user) != null ? ref.rank : void 0) != null) && $rootScope.user.rank !== -1) {
      return checkJsonpData.check({
        code: 4
      });
    }
    $scope.studentId = $scope.passwd = '';
    return $('.ui.form').form({
      studentId: {
        identifier: 'studentId',
        rules: [
          {
            type: 'empty',
            prompt: '学号不能为空！'
          }, {
            type: 'length[10]',
            prompt: '学号不能少于10位！'
          }, {
            type: 'maxLength[10]',
            prompt: '学号不能大于10位！'
          }
        ]
      },
      passwd: {
        identifier: 'passwd',
        rules: [
          {
            type: 'empty',
            prompt: '密码不能为空！'
          }
        ]
      },
      agreement: {
        identifier: 'agreement',
        rules: [
          {
            type: 'checked',
            prompt: '同意用户使用协议方可使用！'
          }
        ]
      }
    }, {
      inline: true,
      on: 'blur',
      onSuccess: function() {
        var params;
        params = {
          fun: 'login',
          passwd: $scope.passwd,
          studentId: $scope.studentId
        };
        return getJsonpData.query(params, 8000, function(data) {
          return $scope.$emit('updateUserInfo');
        });
      }
    });
  };

  scoreController = function($scope, getJsonpData) {
    return getJsonpData.query({}, 8000, function(data) {
      var k, v;
      $scope.data = data.data;
      return $scope.terms = ((function() {
        var ref, results;
        ref = $scope.data;
        results = [];
        for (k in ref) {
          v = ref[k];
          results.push(k);
        }
        return results;
      })()).reverse();
    });
  };

  scoreAllController = function($scope, $location, getJsonpData) {
    if (!$location.search().course) {
      return $location.url('/score');
    }
    return getJsonpData.query({}, 8000, function(data) {
      $scope.info = data.info;
      return $scope.data = data.data;
    });
  };

  scheduleController = function($scope, getJsonpData) {
    return getJsonpData.query({}, 8000, function(data) {
      $scope.data = data.data;
      $scope.info = data.info;
      $('.menu .item').tab();
      return $('.ui.inline.dropdown').dropdown();
    });
  };

  examController = function($scope, getJsonpData) {
    return getJsonpData.query({}, 10000, function(data) {
      return $scope.data = data.data;
    });
  };

  creditController = function($scope, getJsonpData) {
    return getJsonpData.query({}, 10000, function(data) {
      return $scope.data = data.data;
    });
  };

  judgeController = function($scope, $rootScope, $location, $anchorScroll, getJsonpData) {
    getJsonpData.query({}, 10000, function(data) {
      return $scope.data = data.data;
    });
    $scope.judge = function(item) {
      $('.ui.checkbox').checkbox();
      $('.ui.form').form('clear');
      $scope.judging = item;
      return $anchorScroll();
    };
    return $scope.submit = function() {
      var data, flag, i, j, params;
      $rootScope.error = '';
      data = {
        params: $scope.judging.params
      };
      flag = true;
      for (i = j = 0; j < 10; i = ++j) {
        data["a" + i] = $("input[name='a" + i + "']:checked").val();
        if (!data["a" + i]) {
          layer.msg('请确定表单已填写完整。', {
            shift: 6
          });
          return false;
        }
        if (i !== 0 && data["a" + i] !== data["a" + (i - 1)]) {
          flag = false;
        }
      }
      if (flag) {
        layer.msg('不能全部选择相同的选项。', {
          shift: 6
        });
        return false;
      }
      params = {
        fun: 'judge',
        data: angular.toJson(data)
      };
      return getJsonpData.query(params, 10000, function(data) {
        if (data.code === 0) {
          $scope.judging = false;
          return $scope.data = data.data;
        }
      });
    };
  };

  bookController = function($scope, getJsonpData) {
    getJsonpData.query({}, 8000, function(data) {
      return $scope.data = data.data;
    });
    return $scope.renew = function(params) {
      params.fun = 'book';
      return getJsonpData.query(params, 8000, function(data) {
        return $scope.data = data.data;
      });
    };
  };

  bookListController = function($scope, $rootScope, $timeout, $location, getJsonpData) {
    var search;
    $('.ui.form').form({}, {
      onSuccess: function() {
        return $scope.$apply(function() {
          return $scope.search();
        });
      }
    });
    $rootScope.error = '';
    $scope.search = function(key) {
      var ref;
      if (key) {
        $scope.key = key;
      }
      if (!((ref = $scope.key) != null ? ref.length : void 0)) {
        return;
      }
      return $location.search({
        key: $scope.key,
        page: 1,
        rand: Math.random()
      });
    };
    $scope.bookInfo = function(item) {
      if (item.data || item.loading) {
        return;
      }
      item.loading = true;
      return getJsonpData.query({
        fun: 'bookInfo',
        key: item.id
      }, 8000, function(data) {
        item.loading = false;
        return item.data = data.data;
      });
    };
    if ($location.search().key) {
      search = $location.search();
      $scope.key = search.key;
      return getJsonpData.query({
        key: search.key,
        page: search.page
      }, 8000, function(data) {
        $scope.info = data.info;
        $scope.data = data.data;
        return $timeout(function() {
          return $('.ui.accordion').accordion({
            duration: 200,
            exclusive: false
          });
        });
      });
    }
  };

  tuitionController = function($scope, getJsonpData) {
    return getJsonpData.query({}, 8000, function(data) {
      var k, ref, ref1, v;
      $scope.total = (ref = data.data) != null ? ref.total : void 0;
      if ((ref1 = data.data) != null) {
        delete ref1.total;
      }
      $scope.data = data.data;
      return $scope.terms = ((function() {
        var ref2, results;
        ref2 = $scope.data;
        results = [];
        for (k in ref2) {
          v = ref2[k];
          results.push(k);
        }
        return results;
      })()).reverse();
    });
  };

  cardController = function($scope, getJsonpData) {
    return getJsonpData.query({}, 8000, function(data) {
      $scope.info = data.info;
      return $scope.data = data.data;
    });
  };

  failRateController = function($scope, $rootScope, $timeout, getJsonpData) {
    $rootScope.error = '';
    $scope.keys = [];
    $('.ui.search.dropdown').dropdown({
      onChange: function(value) {
        return $scope.search(value);
      }
    });
    $scope.filling = function() {
      return $("[ng-model='key']")[0].value = $scope.key || '';
    };
    $scope.check = function(key) {
      return $timeout(function() {
        if (key === $scope.key && key === '') {
          return $scope.keys = [];
        } else if (key === $scope.key) {
          return $scope.completion(key);
        }
      }, 300);
    };
    $scope.completion = function(key) {
      return getJsonpData.query({
        fun: 'failRateKey',
        key: key
      }, 8000, function(data) {
        $scope.keys = data.data;
        return $timeout(function() {
          return $('.ui.search.dropdown').dropdown('show');
        });
      });
    };
    $scope.search = function(key) {
      var ref;
      $('.ui.search.dropdown').dropdown('hide');
      $('.ui.search.dropdown').dropdown('set text', '');
      if (key) {
        $scope.key = key;
      }
      if (!((ref = $scope.key) != null ? ref.length : void 0)) {
        return;
      }
      $("[ng-model='key']")[0].value = $scope.key;
      $scope.data = [];
      return getJsonpData.query({
        key: $scope.key
      }, 8000, function(data) {
        var item, j, len, ref1, total;
        $scope.data = _.sortBy(data.data, function(item) {
          return -parseFloat(item.rate);
        });
        if ($scope.data.length > 1 && $scope.data[0].name !== $scope.data[0].course) {
          total = {
            'name': '湖南科技大学',
            'all': 0,
            'fail': 0
          };
          ref1 = data.data;
          for (j = 0, len = ref1.length; j < len; j++) {
            item = ref1[j];
            total.all += parseInt(item.all);
            total.fail += parseInt(item.fail);
          }
          total.rate = total.fail / total.all * 100;
          $scope.data.unshift(total);
        }
        return $timeout(function() {
          return $('.progress').progress();
        });
      });
    };
    return $scope.progressColor = function(rate) {
      if (rate <= 2) {
        return ['teal'];
      } else if (rate <= 6) {
        return ['green'];
      } else if (rate <= 12) {
        return ['pink'];
      } else if (rate <= 20) {
        return ['orange'];
      } else {
        return ['red'];
      }
    };
  };

  editUserController = function($scope, $rootScope, $location, getJsonpData) {
    $rootScope.error = '';
    $scope.studentId = '';
    $('.ui.dropdown').dropdown();
    return $('.ui.form').form({
      studentId: {
        identifier: 'studentId',
        rules: [
          {
            type: 'empty',
            prompt: '学号不能为空！'
          }, {
            type: 'length[10]',
            prompt: '学号不能少于10位！'
          }, {
            type: 'maxLength[10]',
            prompt: '学号不能大于10位！'
          }
        ]
      },
      rank: {
        identifier: 'rank',
        rules: [
          {
            type: 'empty',
            prompt: '权限不能为空！'
          }
        ]
      }
    }, {
      inline: true,
      on: 'blur',
      onSuccess: function() {
        var params;
        params = {
          fun: 'editUser',
          studentId: $scope.studentId,
          rank: $("select[name='rank']").val()
        };
        getJsonpData.query(params);
        return false;
      }
    });
  };

  lastUserController = function($scope, getJsonpData) {
    return getJsonpData.query({}, 5000, function(data) {
      return $scope.data = data.data;
    });
  };

  sortByFilter = function() {
    return function(items, predicate, reverse) {
      items = _.sortBy(items, function(item) {
        if (item[predicate] === '优') {
          return 95.02;
        } else if (item[predicate] === '良') {
          return 84.02;
        } else if (item[predicate] === '中') {
          return 74.02;
        } else if (item[predicate] === '及格') {
          return 60.02;
        } else if (item[predicate] === '不及格') {
          return 0;
        } else if (!isNaN(item[predicate]) && item[predicate]) {
          return parseFloat(item[predicate]);
        } else {
          return item[predicate];
        }
      });
      if (reverse) {
        return items;
      } else {
        return items.reverse();
      }
    };
  };

  hnust.controller('navbar', navbarController);

  hnust.controller('login', loginController);

  hnust.controller('user', userController);

  hnust.controller('score', scoreController);

  hnust.controller('scoreAll', scoreAllController);

  hnust.controller('schedule', scheduleController);

  hnust.controller('exam', examController);

  hnust.controller('credit', creditController);

  hnust.controller('judge', judgeController);

  hnust.controller('book', bookController);

  hnust.controller('bookList', bookListController);

  hnust.controller('tuition', tuitionController);

  hnust.controller('card', cardController);

  hnust.controller('failRate', failRateController);

  hnust.controller('editUser', editUserController);

  hnust.controller('lastUser', lastUserController);

  hnust.filter('sortBy', sortByFilter);

}).call(this);
